image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - test

Test Turbo:
    stage: test
    script:
        - mkdir -p /usr/share/man/man1
        - apt update && apt install default-jre -y
        - dotnet tool install --global dotnet-sonarscanner
        - export PATH="$PATH:/root/.dotnet/tools"
        - dotnet sonarscanner begin /d:sonar.host.url="$SONAR_HOST" /d:sonar.login="$SONAR_LOGIN_KEY" /k:"Turbo" /d:sonar.cs.xunit.reportsPaths="**\coverage.cobertura.xml"
        - dotnet test --collect:"XPlat Code Coverage"
        - dotnet sonarscanner end /d:sonar.login="$SONAR_LOGIN_KEY"