image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - test

Test Turbo:
  stage: test
  script:
    - mkdir -p /usr/share/man/man1
    - apt update && apt install default-jre -y
    - export PATH="$PATH:/root/.dotnet/tools"
    - mv Turbo/appsettings.Development.json.example Turbo/appsettings.Development.json
    - mv Turbo/appsettings.Production.json.example Turbo/appsettings.Production.json
    - dotnet test --settings coverlet.runsettings
